CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1000000,1),
	[FirstName] NVARCHAR(30) NOT NULL,
	[LastName] NVARCHAR(30) NOT NULL,
	[Email] NVARCHAR(50) NOT NULL UNIQUE, 
	[PhoneNumber] NVARCHAR(20) NOT NULL UNIQUE, 
	[IdentityID] NVARCHAR(20) NOT NULL UNIQUE, 
	[HashPassword] NVARCHAR(256) NOT NULL,
	[Salt] NVARCHAR(256) NOT NULL
)